# Generated by Django 4.2.12 on 2024-09-05 13:59

from django.db import migrations, models
import vault.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OtherFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(help_text="File name", max_length=255)),
                (
                    "title",
                    models.CharField(help_text="Title of the file", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the file"),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("file_type", models.CharField(blank=True, max_length=50)),
                ("file", models.FileField(upload_to=vault.models.generate_file_name)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(help_text="File name", max_length=255)),
                (
                    "title",
                    models.CharField(help_text="Title of the file", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the file"),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("file_type", models.CharField(blank=True, max_length=50)),
                (
                    "image",
                    models.ImageField(
                        default="uploads/images/default.jpg",
                        upload_to=vault.models.generate_file_name,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(help_text="File name", max_length=255)),
                (
                    "title",
                    models.CharField(help_text="Title of the file", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the file"),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("file_type", models.CharField(blank=True, max_length=50)),
                ("video", models.FileField(upload_to=vault.models.generate_file_name)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
