# Generated by Django 4.2.12 on 2024-09-05 14:06

from django.db import migrations, models
import vault.models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to=vault.models.generate_file_name)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="OtherFile",
        ),
        migrations.DeleteModel(
            name="Picture",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
