# Generated by Django 4.2.12 on 2024-09-05 13:51

from django.db import migrations, models
import django.utils.timezone
import vault.models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(help_text="File name", max_length=255)),
                (
                    "title",
                    models.CharField(help_text="Title of the file", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the file"),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("file_type", models.CharField(blank=True, max_length=50)),
                ("file", models.FileField(upload_to=vault.models.generate_file_name)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(help_text="File name", max_length=255)),
                (
                    "title",
                    models.CharField(help_text="Title of the file", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the file"),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("file_type", models.CharField(blank=True, max_length=50)),
                ("video", models.FileField(upload_to=vault.models.generate_file_name)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="picture",
            name="height",
        ),
        migrations.RemoveField(
            model_name="picture",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="picture",
            name="size_in_bytes",
        ),
        migrations.RemoveField(
            model_name="picture",
            name="width",
        ),
        migrations.AddField(
            model_name="picture",
            name="description",
            field=models.TextField(blank=True, help_text="Description of the file"),
        ),
        migrations.AddField(
            model_name="picture",
            name="file_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="picture",
            name="image",
            field=models.ImageField(
                default="uploads/images/default.jpg",
                upload_to=vault.models.generate_file_name,
            ),
        ),
        migrations.AddField(
            model_name="picture",
            name="title",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Title of the file",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="picture",
            name="upload_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="picture",
            name="filename",
            field=models.CharField(help_text="File name", max_length=255),
        ),
    ]
